# Generated by Django 2.0.5 on 2019-09-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
